Feature/random voted talks
TweetWallFX/TweetwallFX-Devoxx-2023-BE pull request #30
Opened 2023-09-30 13:59 UTC by svenreimers

---
**^Add meaningful description above**

By opening a pull request you confirm that, unless explicitly stated otherwise, the changes -

 - are all your own work, and you have the right to contribute them.
 - are contributed solely under the terms and conditions of the Apache License 2.0 (see section 5 of the license for more information).

Please make sure (eg. `git log`) that all commits have a valid name and email address for you in the Author field.

If you're a first time contributor, see the Contributing guidelines for more information.

2023-09-30 16:57 UTC, reinhapa requested changes, later dismissed
Back to the future with the copyright year 😎

2023-09-30 16:57 UTC, reinhapa commented on cinema/src/main/resources/tweetwall.css
> + * Copyright (c) 2013 TweetWallFX
I guess you meant 2023 here 😎

2023-09-30 16:57 UTC, reinhapa commented on exhibition/src/main/resources/tweetwall.css
> + * Copyright (c) 2013 TweetWallFX
Still wrong year 😎 (blast from the past)

2023-09-30 16:57 UTC, reinhapa commented on hallway/src/main/resources/tweetwall.css
> + * Copyright (c) 2013 TweetWallFX
😎

2023-09-30 19:40 UTC, mklaehn approved these changes, later dismissed

2023-10-01 13:53 UTC, mklaehn approved these changes

2023-10-01 13:57 UTC, merged